package com.xl.mbgdemo1.model;

public class Tb1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1.a
     *
     * @mbg.generated Fri Jan 10 16:21:52 CST 2020
     */
    private Integer a;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1.a
     *
     * @return the value of tb1.a
     *
     * @mbg.generated Fri Jan 10 16:21:52 CST 2020
     */
    public Integer getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1.a
     *
     * @param a the value for tb1.a
     *
     * @mbg.generated Fri Jan 10 16:21:52 CST 2020
     */
    public void setA(Integer a) {
        this.a = a;
    }
}